name: CI

# TODO: chore -> main
on:
  pull_request:
    branches:
      - chore/*

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/workflows/install-dependencies.yml

  lint:
      runs-on: ubuntu-latest
      needs: install-dependencies
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Lint code
          uses: ./.github/workflows/lint.yml

  build-android:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Build Android
          uses: ./.github/workflows/build-android.yml